# Generated by Django 4.2.11 on 2024-04-06 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("product_type", models.CharField(default="", max_length=50)),
                ("farm_size", models.FloatField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(default="", max_length=50)),
                ("zipcode", models.CharField(default="", max_length=10)),
                ("state", models.CharField(default="", max_length=50)),
                ("country", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(null=True)),
                ("available_quantity", models.PositiveIntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity_type", models.CharField(max_length=50)),
                ("price_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="farmer.farmerprofile",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
