# Generated by Django 4.2.11 on 2024-04-01 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('product_type', models.CharField(default='', max_length=50)),
                ('farm_size', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(default='', max_length=50)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('state', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
