# Generated by Django 4.2.11 on 2024-04-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0003_product_customerorders"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomerOrders",),
    ]
