# Generated by Django 4.2.11 on 2024-04-02 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0004_delete_customerorders"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_amount_to_pay",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Farmer Not Approved"),
                            (2, "Approved & Out for Delivery"),
                            (3, "Delivered"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "order_no",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="farmer.farmerprofile",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_orders",
                        to="farmer.farmerprofile",
                    ),
                ),
                ("products", models.ManyToManyField(to="farmer.product")),
            ],
            options={"ordering": ["-ordered_at"],},
        ),
    ]
