# Generated by Django 4.2.11 on 2024-04-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_farmerorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerOrders',
        ),
    ]
