# Generated by Django 4.2.11 on 2024-04-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/images"),
        ),
    ]
