# Generated by Django 4.2.11 on 2024-04-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0008_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="description", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="farmer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="farmer.farmerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
