export const orders = [
  {
    orderNo: "1230",
    dateOrdered: "28-03-2024",
    orderedBy: "RANADE ENTERPRISES, RAJAPUR",
    product: "FRESH MANGO, RATNAGIRI ALPHONSO",
    quantity: "20 dozen",
    price: "Rs. 4000",
    deliveryFee: "Rs. 100",
    deliveryBy: "29-03-2024",
    totalAmountToBePaid: "Rs. 4100",
    status: "OUT FOR DELIVERY",
  },
  {
    orderNo: "1231",
    dateOrdered: "29-03-2024",
    orderedBy: "ABC Fruits, Mumbai",
    product: "ORGANIC APPLES",
    quantity: "10 kg",
    price: "Rs. 800",
    deliveryFee: "Rs. 50",
    deliveryBy: "30-03-2024",
    totalAmountToBePaid: "Rs. 850",
    status: "DELIVERED",
  },
  {
    orderNo: "1232",
    dateOrdered: "30-03-2024",
    orderedBy: "Green Farms, Pune",
    product: "FRESH TOMATOES",
    quantity: "15 kg",
    price: "Rs. 600",
    deliveryFee: "Rs. 80",
    deliveryBy: "31-03-2024",
    totalAmountToBePaid: "Rs. 680",
    status: "PENDING",
  },
  {
    orderNo: "1233",
    dateOrdered: "31-03-2024",
    orderedBy: "Natures Bounty, Bangalore",
    product: "ORGANIC BANANAS",
    quantity: "25 dozen",
    price: "Rs. 1200",
    deliveryFee: "Rs. 150",
    deliveryBy: "01-04-2024",
    totalAmountToBePaid: "Rs. 1350",
    status: "OUT FOR DELIVERY",
  },
  {
    orderNo: "1234",
    dateOrdered: "01-04-2024",
    orderedBy: "Harvest Farms, Chennai",
    product: "FRESH ORANGES",
    quantity: "30 dozen",
    price: "Rs. 1500",
    deliveryFee: "Rs. 120",
    deliveryBy: "02-04-2024",
    totalAmountToBePaid: "Rs. 1620",
    status: "DELIVERED",
  },
  {
    orderNo: "1235",
    dateOrdered: "02-04-2024",
    orderedBy: "Sunny Farms, Hyderabad",
    product: "SWEET PINEAPPLES",
    quantity: "5 pieces",
    price: "Rs. 300",
    deliveryFee: "Rs. 30",
    deliveryBy: "03-04-2024",
    totalAmountToBePaid: "Rs. 330",
    status: "PENDING",
  },
  {
    orderNo: "1236",
    dateOrdered: "03-04-2024",
    orderedBy: "Green World, Delhi",
    product: "ORGANIC SPINACH",
    quantity: "2 kg",
    price: "Rs. 200",
    deliveryFee: "Rs. 20",
    deliveryBy: "04-04-2024",
    totalAmountToBePaid: "Rs. 220",
    status: "OUT FOR DELIVERY",
  },
  {
    orderNo: "1237",
    dateOrdered: "04-04-2024",
    orderedBy: "Fruitful Gardens, Kolkata",
    product: "FRESH GRAPES",
    quantity: "10 kg",
    price: "Rs. 500",
    deliveryFee: "Rs. 60",
    deliveryBy: "05-04-2024",
    totalAmountToBePaid: "Rs. 560",
    status: "DELIVERED",
  },
  {
    orderNo: "1238",
    dateOrdered: "05-04-2024",
    orderedBy: "Eco-Friendly Farms, Ahmedabad",
    product: "ORGANIC CARROTS",
    quantity: "3 kg",
    price: "Rs. 150",
    deliveryFee: "Rs. 25",
    deliveryBy: "06-04-2024",
    totalAmountToBePaid: "Rs. 175",
    status: "PENDING",
  },
  {
    orderNo: "1241",
    dateOrdered: "08-04-2024",
    orderedBy: "Organic Delights, Mumbai",
    product: "Fresh Lemons",
    quantity: "10 kg",
    price: "Rs. 300",
    deliveryFee: "Rs. 30",
    deliveryBy: "09-04-2024",
    totalAmountToBePaid: "Rs. 330",
    status: "New Orders",
  },
  {
    orderNo: "1239",
    dateOrdered: "06-04-2024",
    orderedBy: "Healthy Harvest, Chandigarh",
    product: "FRESH STRAWBERRIES",
    quantity: "1 kg",
    price: "Rs. 100",
    deliveryFee: "Rs. 15",
    deliveryBy: "07-04-2024",
    totalAmountToBePaid: "Rs. 115",
    status: "OUT FOR DELIVERY",
  },
  {
    orderNo: "1240",
    dateOrdered: "07-04-2024",
    orderedBy: "Fresh Farms, Bangalore",
    product: "Ripe Avocados",
    quantity: "15 pieces",
    price: "Rs. 450",
    deliveryFee: "Rs. 50",
    deliveryBy: "08-04-2024",
    totalAmountToBePaid: "Rs. 500",
    status: "New Orders",
  },
];
