# Generated by Django 4.2.11 on 2024-04-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_cartitem_order_orderitem_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
