# Generated by Django 4.1.13 on 2024-04-01 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authApp", "0016_alter_otpverification_expiry_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="user",),
        migrations.AlterField(
            model_name="otpverification",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 1, 13, 37, 3, 729836, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
