# Generated by Django 4.1.13 on 2024-04-01 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authApp", "0021_alter_otpverification_expiry_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 1, 15, 12, 9, 522185, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
