# Generated by Django 4.1.13 on 2024-04-01 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authApp", "0022_alter_otpverification_expiry"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="user",),
        migrations.AlterField(
            model_name="otpverification",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 1, 15, 15, 11, 687568, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
