# Generated by Django 4.1.13 on 2024-04-01 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authApp", "0025_alter_otpverification_expiry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 1, 15, 19, 42, 455785, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
