# Generated by Django 4.2.11 on 2024-04-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customer_type',
            new_name='user_type',
        ),
    ]
